services:
  iptv-downloader:
    build: .
    container_name: iptv-downloader
    ports:
      - "2233:2233"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    restart: unless-stopped
