services:
  iptv-downloader:
    image: ghcr.io/richrdj/iptv-downloader:latest
    container_name: iptv-downloader
    ports:
      - "2233:2233"
    volumes:
      - iptv_config:/config
      - iptv_downloads:/downloads
    restart: unless-stopped

volumes:
  iptv_config:
  iptv_downloads:
