services:
  iptv-downloader:
    image: ghcr.io/richrdj/iptv-downloader:latest
    ports:
      - target: 2233
        published: 2233
        mode: host
    volumes:
      - iptv_config:/config
      - type: bind
        source: /mnt/video/_downloads
        target: /downloads
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  iptv_config:
